produk:
  get:
    tags:
      - Produk
    summary: Ambil semua produk
    description: |
      Mengambil daftar produk.
      Mendukung pagination dan pencarian.
    security: []
    parameters:
      - name: page
        in: query
        required: false
        description: Nomor halaman
        schema:
          type: integer
          example: 1
      - name: limit
        in: query
        required: false
        description: Jumlah data per halaman
        schema:
          type: integer
          example: 10
      - name: q
        in: query
        required: false
        description: Kata kunci pencarian produk
        schema:
          type: string
          example: kaos
    responses:
      "200":
        description: Data produk berhasil diambil
      "500":
        description: Gagal mengambil data produk

  post:
    tags:
      - Produk
    summary: Tambah produk baru
    description: Endpoint untuk menambahkan produk baru (Admin only)
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            required:
              - nama_produk
              - harga
              - estimasi_pengerjaan
            properties:
              nama_produk:
                type: string
                example: Kaos Sablon
              deskripsi:
                type: string
                example: Kaos bahan cotton combed
              harga:
                type: number
                example: 75000
              estimasi_pengerjaan:
                type: number
                example: 5
              bahan:
                type: string
                example: Cotton Combed 30s
              foto:
                type: string
                format: binary
    responses:
      "201":
        description: Produk berhasil dibuat
      "401":
        description: Unauthorized
      "500":
        description: Gagal membuat produk

produkById:
  get:
    tags:
      - Produk
    summary: Ambil detail produk
    description: Mengambil detail produk berdasarkan ID
    security: []
    parameters:
      - name: id
        in: path
        required: true
        description: ID produk
        schema:
          type: string
    responses:
      "200":
        description: Data produk berhasil diambil
      "404":
        description: Produk tidak ditemukan
      "500":
        description: Gagal mengambil produk

  put:
    tags:
      - Produk
    summary: Update produk
    description: Memperbarui data produk (Admin only)
    security:
      - bearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        description: ID produk
        schema:
          type: string
    requestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              nama_produk:
                type: string
              deskripsi:
                type: string
              harga:
                type: number
              estimasi_pengerjaan:
                type: number
              bahan:
                type: string
              foto:
                type: string
                format: binary
    responses:
      "200":
        description: Produk berhasil diperbarui
      "401":
        description: Unauthorized
      "404":
        description: Produk tidak ditemukan
      "500":
        description: Gagal memperbarui produk

  delete:
    tags:
      - Produk
    summary: Hapus produk
    description: Menghapus produk berdasarkan ID (Admin only)
    security:
      - bearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        description: ID produk
        schema:
          type: string
    responses:
      "200":
        description: Produk berhasil dihapus
      "401":
        description: Unauthorized
      "404":
        description: Produk tidak ditemukan
      "500":
        description: Gagal menghapus produk
